### ISSUE TITLE
[Translation] A particular document appears to be running into an error 

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#3377]
### Background
A particular document appears to be running into an error during the the file upload process. The error is: 

```none
Error occured during upload process for: src/content/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips.mdx
Error: Error: Unable to serialize component: 'br'. You need to specify a serializer in 'scripts/actions/utils/handlers.js'
Error: Unable to serialize component: 'br'. You need to specify a serializer in 'scripts/actions/utils/handlers.js'
    at mdxElement (/home/runner/work/docs-website/docs-website/scripts/actions/serialize-mdx.js:17:11)
    at one (/home/runner/work/docs-website/docs-website/node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/one.js:37:51)
    at all (/home/runner/work/docs-website/docs-website/node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/all.js:16:14)
    at paragraph (/home/runner/work/docs-website/docs-website/node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/handlers/paragraph.js:8:23)
    at one (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/one.js:37:51)
    at all (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/all.js:16:14)
    at serializeComponent (/home/runner/work/docs-website/docs-website/scripts/actions/utils/serialization-helpers.js:97:13)
    at Object.serialize (/home/runner/work/docs-website/docs-website/scripts/actions/utils/handlers.js:226:7)
    at mdxElement (/home/runner/work/docs-website/docs-website/scripts/actions/serialize-mdx.js:22:18)
    at one (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/one.js:37:51)
```
[Link](https://github.com/newrelic/docs-website/runs/3224868355?check_suite_focus=true) to failure run.

I dont think this problem is necessarily limited to this one document, but currently, only this document is experiencing it.

Additionally, this document will continue to fail the upload process until we fix it.

### Acceptance Criteria
- [ ] file uploads w/o issue

**Comment by jpvajda** [comment]
since this is a single document, I put a P3 on it and tagged it for consideration in our MT epic. (milestone)
