### ISSUE TITLE
[Translation Workflow] Problematic file causing send translation workflow to fail

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#3913]
## Summary
[The most recent run](https://github.com/newrelic/docs-website/runs/3605265246?check_suite_focus=true) of the send translation workflow failed due to a single file not being uploaded.

The specific file & error:
```none
Error occured during upload process for: src/content/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration.mdx
Error: Error: Unable to serialize component: 'nobr'. You need to specify a serializer in 'scripts/actions/utils/handlers.js'
Error: Unable to serialize component: 'nobr'. You need to specify a serializer in 'scripts/actions/utils/handlers.js'
    at mdxElement (/home/runner/work/docs-website/docs-website/scripts/actions/serialize-mdx.js:17:11)
    at one (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/one.js:37:51)
    at all (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/all.js:16:14)
    at serializeComponent (/home/runner/work/docs-website/docs-website/scripts/actions/utils/serialization-helpers.js:97:13)
    at Object.serialize (/home/runner/work/docs-website/docs-website/scripts/actions/utils/handlers.js:217:7)
    at mdxElement (/home/runner/work/docs-website/docs-website/scripts/actions/serialize-mdx.js:22:18)
    at one (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/one.js:37:51)
    at all (/home/runner/work/docs-website/docs-website/node_modules/mdast-util-to-hast/lib/all.js:16:14)
    at serializeComponent (/home/runner/work/docs-website/docs-website/scripts/actions/utils/serialization-helpers.js:97:13)
    at Object.serialize (/home/runner/work/docs-website/docs-website/scripts/actions/utils/handlers.js:208:7)
```

## Acceptance Criteria
- [ ] fix failing file

**Comment by nr-kkenney** [comment]
a few more files failed in the most recent run: https://github.com/newrelic/docs-website/runs/3762530772?check_suite_focus=true

files are:
src/content/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration.mdx
src/content/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration.mdx
src/content/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration.mdx
src/content/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration.mdx
