### ISSUE TITLE
Fatal Exception: yw9: HTTP 403

### ISSUE THREAD

**Issue by NG-Gaurav** [newrelic/docs-website#9221]
Fatal Exception: yw9: HTTP 403 
       at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
       at com.newrelic.agent.android.instrumentation.okhttp3.CallbackExtension.onResponse(CallbackExtension.java:42)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by NG-Gaurav** [comment]
agent version

**Comment by x8a** [comment]
Hey, @NG-Gaurav! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
